packages:
  - internal/*
  - internal/lint-configs/*
  - packages/*
  - packages/core/base/*
  - packages/core/ui-kit/*
  - packages/core/forward/*
  - packages/core/*
  - packages/effects/*
  - packages/business/*
  - apps/*
  - scripts/*

catalog:
  '@changesets/changelog-github': ^0.5.1
  '@changesets/cli': ^2.29.5
  '@changesets/git': ^3.0.4
  '@clack/prompts': ^0.10.1
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@ctrl/tinycolor': ^4.1.0
  '@eslint/js': ^9.30.1
  '@iconify/tailwind4': ^1.0.6
  '@iconify/vue': ^5.0.0
  '@intlify/core-base': ^11.1.7
  '@intlify/unplugin-vue-i18n': ^6.0.8
  '@manypkg/get-packages': ^3.0.0
  '@playwright/test': ^1.53.2
  '@pnpm/workspace.read-manifest': ^1000.2.0
  '@tailwindcss/typography': ^0.5.16
  '@tanstack/vue-store': ^0.7.1
  '@types/archiver': ^6.0.3
  '@types/eslint': ^9.6.1
  '@types/lodash-es': ^4.17.12
  '@types/node': ^24.3.0
  '@types/nprogress': ^0.2.3
  '@types/postcss-import': ^14.0.3
  '@types/qrcode': ^1.5.5
  '@types/qs': ^6.14.0
  '@types/sortablejs': ^1.15.8
  '@typescript-eslint/eslint-plugin': ^8.35.1
  '@typescript-eslint/parser': ^8.35.1
  '@vee-validate/zod': ^4.15.1
  '@vitejs/plugin-vue': ^6.0.1
  '@vitejs/plugin-vue-jsx': ^5.0.1
  '@vue/test-utils': ^2.4.6
  '@vueuse/core': ^13.4.0
  '@vueuse/integrations': ^13.4.0
  '@vueuse/motion': ^3.0.3
  archiver: ^7.0.1
  autoprefixer: ^10.4.21
  axios: ^1.10.0
  cac: ^6.7.14
  chalk: ^5.4.1
  circular-dependency-scanner: ^2.3.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  commitlint-plugin-function-rules: ^4.0.2
  consola: ^3.4.2
  cross-env: ^7.0.3
  cspell: ^8.19.4
  cssnano: ^7.0.7
  cz-git: ^1.11.2
  czg: ^1.11.1
  dayjs: ^1.11.13
  defu: ^6.1.4
  depcheck: ^1.4.7
  dotenv: ^16.6.1
  eslint: ^9.30.1
  eslint-config-turbo: ^2.5.4
  eslint-plugin-command: ^3.3.1
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-jsdoc: ^50.8.0
  eslint-plugin-jsonc: ^2.20.1
  eslint-plugin-n: ^17.20.0
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^4.15.0
  eslint-plugin-prettier: ^5.5.1
  eslint-plugin-regexp: ^2.9.0
  eslint-plugin-unicorn: ^59.0.1
  eslint-plugin-unused-imports: ^4.1.4
  eslint-plugin-vitest: ^0.5.4
  eslint-plugin-vue: ^10.2.0
  execa: ^9.6.0
  find-up: ^7.0.0
  get-port: ^7.1.0
  globals: ^16.3.0
  h3: ^1.15.3
  happy-dom: ^17.6.3
  is-ci: ^4.1.0
  jsonc-eslint-parser: ^2.4.0
  lefthook: ^1.11.14
  lodash-es: 4.17.21
  lucide-vue-next: ^0.507.0
  medium-zoom: ^1.1.0
  nprogress: ^0.2.0
  ora: ^8.2.0
  pinia: ^3.0.3
  pkg-types: ^2.2.0
  playwright: ^1.53.2
  postcss: ^8.5.6
  postcss-antd-fixes: ^0.2.0
  postcss-html: ^1.8.0
  postcss-import: ^16.1.1
  postcss-preset-env: ^10.2.4
  postcss-scss: ^4.0.9
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.13
  publint: ^0.3.12
  qrcode: ^1.5.4
  qs: ^6.14.0
  radix-vue: ^1.9.17
  resolve.exports: ^2.0.3
  rimraf: ^6.0.1
  rollup: ^4.44.1
  rollup-plugin-visualizer: ^5.14.0
  sass: ^1.89.2
  secure-ls: ^2.0.0
  sortablejs: ^1.15.6
  tailwind-merge: ^2.6.0
  tailwindcss: ^4.1.12
  theme-colors: ^0.1.0
  tippy.js: ^6.3.7
  turbo: ^2.5.4
  typescript: ^5.8.3
  unbuild: ^3.6.1
  vee-validate: ^4.15.1
  vite: ^7.1.2
  vite-plugin-compression: ^0.5.1
  vite-plugin-dts: ^4.5.4
  vite-plugin-html: ^3.2.2
  vite-plugin-lazy-import: ^1.0.7
  vite-plugin-vue-devtools: ^7.7.7
  vitest: ^3.2.4
  vue: ^3.5.17
  vue-eslint-parser: ^10.2.0
  vue-i18n: ^11.1.7
  vue-json-viewer: ^3.0.4
  vue-router: ^4.5.1
  vue-tippy: ^6.7.1
  vue-tsc: 2.2.10
  watermark-js-plus: ^1.6.2
  zod: ^3.25.67
  zod-defaults: ^0.1.3
